$(document).ready(function () {
    var main1 = $("#main-1")
    var main2 = $("#main-2")
    var main3 = $("#main-3")
    var main4 = $("#main-4")
    main1.css("display", "flex")
    main2.css("display", "none")
    main3.css("display", "none")
    main4.css("display", "none")
    $(document).on("click", ".btn-web", function () {
        main1.css("display", "flex")
        main2.css("display", "none")
		main3.css("display", "none")
		main4.css("display", "none")
		$('.btn-web').addClass('active-btn')
		$('.btn-app').removeClass('active-btn')
		$('.btn-package').removeClass('active-btn')
		$('.btn-miniprogram').removeClass('active-btn')
    })
    $(document).on("click", ".btn-app", function () {
        main1.css("display", "none")
		main2.css("display", "flex")
		main3.css("display", "none")
		main4.css("display", "none")
		$("#mian-3").css("display", "none")
		$('.btn-app').addClass('active-btn')
		$('.btn-web').removeClass('active-btn')
		$('.btn-package').removeClass('active-btn')
		$('.btn-miniprogram').removeClass('active-btn')
	})
	$(document).on("click", ".btn-miniprogram", function () {
        main1.css("display", "none")
        main2.css("display", "none")
		main3.css("display", "flex")
		main4.css("display", "none")
		$('.btn-miniprogram').addClass('active-btn')
		$('.btn-package').removeClass('active-btn')
		$('.btn-web').removeClass('active-btn')
		$('.btn-app').removeClass('active-btn')
    })
    $(document).on("click", ".btn-package", function () {
        main1.css("display", "none")
        main2.css("display", "none")
		main3.css("display", "none")
		main4.css("display", "flex")
		$('.btn-package').addClass('active-btn')
		$('.btn-web').removeClass('active-btn')
		$('.btn-app').removeClass('active-btn')
		$('.btn-miniprogram').removeClass('active-btn')
	})
	$('.close-dialog').on('click',function(){
		$('.dialog').css('display','none')
	})
	$('.p').on('click',function () {
		$('.dialog').css('display','block')
	  })
});


